name: dashboard_busbanz_practice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/kid_sophia.png
    - assets/images/kid_wade.png
    - assets/images/kid_floyd.png
    - assets/images/kid_veronica.png
    - assets/images/imagen_de_andrea.png
    - assets/images/imagen_de_conductor.png
    - assets/images/imagen_de_carro.png
    - assets/images/fonts/Poppins/Poppins-Black.ttf
    - assets/images/fonts/Poppins/Poppins-BlackItalic.ttf
    - assets/images/fonts/Poppins/Poppins-Bold.ttf
    - assets/images/fonts/Poppins/Poppins-BoldItalic.ttf
    - assets/images/fonts/Poppins/Poppins-ExtraBold.ttf
    - assets/images/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
    - assets/images/fonts/Poppins/Poppins-ExtraLight.ttf
    - assets/images/fonts/Poppins/Poppins-ExtraLightItalic.ttf
    - assets/images/fonts/Poppins/Poppins-Italic.ttf
    - assets/images/fonts/Poppins/Poppins-Light.ttf
    - assets/images/fonts/Poppins/Poppins-LightItalic.ttf
    - assets/images/fonts/Poppins/Poppins-Medium.ttf
    - assets/images/fonts/Poppins/Poppins-MediumItalic.ttf
    - assets/images/fonts/Poppins/Poppins-Regular.ttf
    - assets/images/fonts/Poppins/Poppins-SemiBold.ttf
    - assets/images/fonts/Poppins/Poppins-SemiBoldItalic.ttf

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/images/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/images/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/images/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/images/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/images/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/images/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/images/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/images/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/images/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/images/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/images/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/images/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/images/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/images/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/images/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/images/fonts/Poppins/Poppins-SemiBoldItalic.ttf






